add orders to admin
TopTrip-ge/top-trip pull request #100
Opened 2022-11-08 11:00 UTC by davin01001

show orders in admin

2022-11-08 16:37 UTC, pavelsokolov21 commented
.idea не должно быть в проекте

2022-11-08 16:46 UTC, pavelsokolov21 requested changes

2022-11-08 16:46 UTC, pavelsokolov21 commented on src/pages/admin/order-info/components/form/form-hooks.ts
> +  // const getHelperText = (fieldName: FieldNames) => formik.touched[fieldName] && formik.errors[fieldName];
!

2022-11-08 16:46 UTC, pavelsokolov21 commented on src/pages/admin/order-info/components/form/form-hooks.ts
> +        // helperText: getHelperText(ORDER_FIELD_NAMES.NAME),
!

2022-11-08 16:46 UTC, pavelsokolov21 commented on src/pages/admin/order-info/components/form/form-hooks.ts
> +    //   key: ORDER_FIELD_NAMES.DATETIME,
!

2022-11-08 16:46 UTC, pavelsokolov21 commented on src/pages/admin/order-info/components/form/form-hooks.ts
> +        // helperText: getHelperText(ORDER_FIELD_NAMES.PHONE),
!

2022-11-08 16:46 UTC, pavelsokolov21 commented on src/pages/admin/order-info/components/form/form-hooks.ts
> +        // helperText: getHelperText(ORDER_FIELD_NAMES.EMAIL),
!

2022-11-08 16:46 UTC, pavelsokolov21 commented on src/pages/admin/order-info/components/form/form-hooks.ts
> +        // helperText: getHelperText(ORDER_FIELD_NAMES.DEPARTURE),
!

2022-11-08 16:46 UTC, pavelsokolov21 commented on src/pages/admin/order-info/components/form/form-hooks.ts
> +        // helperText: getHelperText(ORDER_FIELD_NAMES.DESTINATION),
!

2022-11-08 16:46 UTC, pavelsokolov21 commented on src/pages/admin/order-info/components/form/form-hooks.ts
> +        // helperText: getHelperText(ORDER_FIELD_NAMES.PRICE),
!

2022-11-08 16:46 UTC, pavelsokolov21 commented on src/pages/admin/order-info/components/form/form-hooks.ts
> +        // helperText: getHelperText(ORDER_FIELD_NAMES.CAR),
!

2022-11-08 16:46 UTC, pavelsokolov21 commented on src/pages/admin/order-info/components/form/form-hooks.ts
> +        // helperText: getHelperText(ORDER_FIELD_NAMES.COMMENT),
!

2022-11-08 16:46 UTC, pavelsokolov21 commented on src/theme/main-theme.tsx
> +// import { orange } from "@mui/material/colors";
!

2022-11-09 06:41 UTC, davin01001 commented
agree

2022-11-09 06:55 UTC, pavelsokolov21 approved these changes

2022-11-09 08:36 UTC, merged