feat: added database request and changed style for dropdown
TopTrip-ge/top-trip pull request #25
Opened 2022-06-15 18:16 UTC by KoTuK2306

2022-06-16 10:56 UTC, pavelsokolov21 requested changes

2022-06-16 10:56 UTC, pavelsokolov21 commented on src/pages/home/home.tsx
> +/* eslint-disable @typescript-eslint/no-unused-vars */
удалить

2022-06-16 10:56 UTC, pavelsokolov21 commented on src/firebase-common/hooks/use-collection.ts
> +  const firebaseApp = initializeApp(firebaseConfig);
```suggestion
  const { firestore }= useContext(FirebaseContext);

```

2022-06-16 10:56 UTC, pavelsokolov21 commented on src/firebase-common/hooks/use-collection.ts
> +import { useCollection as useCollectionHook } from "react-firebase-hooks/firestore";
добавить хух в `index.ts`

2022-06-16 10:56 UTC, pavelsokolov21 commented on src/firebase-common/hooks/use-collection.ts
> +  const [database] = useCollectionHook(collection(getFirestore(firebaseApp), "destinations"), {
этот хук должен быть общим. Сейчас он работает только для `destinations`

2022-06-16 10:56 UTC, pavelsokolov21 commented on src/firebase-common/hooks/use-collection.ts
> +  database?.docs.map((doc) => {
сайд-эффект с сортирвкой в хуке. Любая функция делает одно действие самостоятельно. Этого кода тут быть не должно!

2022-06-16 10:56 UTC, pavelsokolov21 commented on src/firebase-common/hooks/use-collection.ts
> +  return { destinations };
посмотри пример использования `useDocument`. Помимо данных нам нужно обрабатывать загрузку и ошибку

2022-06-16 10:56 UTC, pavelsokolov21 commented on src/pages/home/home.tsx
> +const SelectDestination = (id: string, direction: string, setDirection: any, values: any, label: string) => {
никаких `any`

2022-06-16 10:56 UTC, pavelsokolov21 commented on src/pages/home/home.tsx
> +    <Select MenuProps={{ style: { height: "60vh" } }} id={id} value={direction} label={label} onChange={setDirection}>
`60vh`??

2022-06-16 10:56 UTC, pavelsokolov21 commented on src/pages/home/home.tsx
> +              margin: "25vh auto 0 auto",
`25vh`??

2022-06-16 10:56 UTC, pavelsokolov21 commented on src/theme/main-theme.tsx
> +
ненужный пробел

2022-06-16 10:56 UTC, pavelsokolov21 commented on src/firebase-common/hooks/use-collection.ts
> +export const useCollection = () => {
хук стоит сделать с дженериком, чтобы протипизировать выходные данные

2022-06-17 20:59 UTC, pavelsokolov21 requested changes

2022-06-17 20:59 UTC, pavelsokolov21 commented on src/pages/home/components/search/search.tsx
> +const SelectDestination: FC<SelectDestinationTypes> = ({ id, direction, setDirection, values, label }) => {
Вынести

2022-06-17 20:59 UTC, pavelsokolov21 commented on src/pages/home/components/search/search.tsx
> +interface SelectDestinationTypes {
вынести

2022-06-17 20:59 UTC, pavelsokolov21 commented on src/pages/home/components/search/search.tsx
> +import { Destination } from "../../../../interfaces/destination";
алиасы

2022-06-17 20:59 UTC, pavelsokolov21 commented on src/pages/home/components/search/search.tsx
> +import { sortArray } from "../../../../utils/sort-array";
алиасы

2022-06-17 20:59 UTC, pavelsokolov21 commented on src/pages/home/components/search/search.tsx
>  import { DESTINATIONS } from "../../enums";
алиасы

2022-06-17 20:59 UTC, pavelsokolov21 commented on src/pages/home/components/search/search.tsx
> +  const [database] = useCollection<Destination>("destinations");
тут уже определённая коллекция, а не абстрактная database

2022-06-17 20:59 UTC, pavelsokolov21 commented on src/utils/sort-array.ts
> +  data: () => {
не обязательно будет возвращать этот объект

2022-06-17 20:59 UTC, pavelsokolov21 commented on src/utils/sort-array.ts
> +    arrayElementId: arrayElement.id,
не обязательно будут эти поля

2022-06-17 20:59 UTC, pavelsokolov21 commented on src/utils/sort-array.ts
> +export const sortArray = (database: QuerySnapshot<Destination> | undefined) => {
не обязательно Destination

2022-06-17 20:59 UTC, pavelsokolov21 commented on src/utils/sort-array.ts
> +export const sortArray = (database: QuerySnapshot<Destination> | undefined) => {
```suggestion
export const sortArray = (database?: QuerySnapshot<Destination>) => {

```

2022-06-17 20:59 UTC, pavelsokolov21 commented on src/utils/sort-array.ts
> +export const sortArray = (database: QuerySnapshot<Destination> | undefined) => {
сейчас сортирует только в одну сторону, так что название не совсем корректно

2022-06-17 20:59 UTC, pavelsokolov21 commented on src/pages/home/components/search/search.tsx
> +  const destinationsArray = sortArray(database)?.map(({ arrayElementId, arrayElementName }) => (
```suggestion
  const destinations = sortArray(database)?.map(({ arrayElementId, arrayElementName }) => (
```

2022-06-19 21:32 UTC, KoTuK2306 commented on src/pages/home/components/search/search.tsx
> +            <Typography variant="h5">Loading...</Typography>
Я бы поискал в муи спинер, просто текст эт скучн

2022-06-19 21:34 UTC, pavelsokolov21 commented on src/pages/home/components/search/search.tsx
> +            <Typography variant="h5">Loading...</Typography>
Сам сделаешь ;)

2022-06-19 21:41 UTC, pavelsokolov21 approved these changes

2022-06-19 21:43 UTC, merged