Feature/add destination button
TopTrip-ge/top-trip pull request #58
Opened 2022-07-11 14:59 UTC by KoTuK2306

2022-07-15 20:25 UTC, pavelsokolov21 requested changes

2022-07-15 20:25 UTC, pavelsokolov21 commented on src/pages/home/components/search/components/select-where-destination/select-where-destination.tsx
> +        <WithSkeleton animation="pulse" isLoading={false} sx={{ minHeight: SKELETON_MIN_HEIGHT }}>
этот участок кода повторяется выше, его стоит вынести как-то. Тут отличие только в наличии кнопки удаления и гриде

2022-07-15 20:25 UTC, pavelsokolov21 commented on src/pages/home/components/search/search-hooks.ts
> +    const valueId = value?.id;
зачем нам эти константы?

2022-07-15 20:25 UTC, pavelsokolov21 commented on src/pages/home/components/search/search-hooks.ts
> +  const handleChangeWhere = (arrayHelpers: FieldArrayRenderProps, index: number, value: any | null) => {
any

2022-07-15 20:25 UTC, pavelsokolov21 commented on src/pages/home/components/search/search-hooks.ts
> +    arrayHelpers.replace(index, { id: value.id, label: value.label });
выглядит так, что можно просто передавать `value`

2022-07-15 20:25 UTC, pavelsokolov21 commented on src/pages/home/components/search/components/select-where-destination/select-where-destination.tsx
> +  label: SearchDestination;
мне кажется, что это всё-таки `value`, а не `label`, так как `SearchDestination` содержит `label` и `id`

2022-07-15 20:25 UTC, pavelsokolov21 commented on src/pages/home/components/search/search-hooks.ts
> +      .of(yup.object().shape({ id: yup.string().required().min(3), label: yup.string().required().min(3) }))
почему `min(3)`?

2022-07-15 20:25 UTC, pavelsokolov21 commented on src/utils/form.ts
> +export const getErrorFromFieldArray = <F extends string>(field: F, fieldErrors: any) => {
пока нет идей, как фиксить `any`?

2022-07-15 20:27 UTC, pavelsokolov21 commented
при выборе поля моргают все `Куда`. Нужно посмотреть

2022-07-15 20:29 UTC, pavelsokolov21 requested changes

2022-07-15 20:29 UTC, pavelsokolov21 commented on src/pages/home/components/search/search.tsx
> +                        menuItems={menuItems}
давай назовём `options`

2022-07-16 09:09 UTC, KoTuK2306 commented on src/pages/home/components/search/search-hooks.ts
> +      .of(yup.object().shape({ id: yup.string().required().min(3), label: yup.string().required().min(3) }))
Потому что изначально строка имеет длину 1, а 3 это для проверки заполнения поля, чтобы наверняка

2022-07-16 13:06 UTC, pavelsokolov21 requested changes

2022-07-16 13:06 UTC, pavelsokolov21 commented on src/interfaces/search-form.ts
> +  where: { id: string; label: string }[];
интерфейс для `where` существует у нас в базе `SearchDestination`

2022-07-16 13:06 UTC, pavelsokolov21 commented on src/pages/home/components/search/components/select-where-destination/select-where-destination.tsx
> +import { FC } from "react";
index.ts

2022-07-16 13:06 UTC, pavelsokolov21 commented on src/pages/home/components/search/components/select-destination/select-destinations.tsx
>  import { FC, ReactNode } from "react";
index.ts

2022-07-16 13:06 UTC, pavelsokolov21 commented on src/pages/home/components/search/search-hooks.ts
>    const formik = useFormik({
```suggestion
  const formik = useFormik<SearchForm>({
```

2022-07-16 13:06 UTC, pavelsokolov21 commented on src/pages/home/components/search/search.tsx
> +                        // eslint-disable-next-line react/no-array-index-key
убрать и использовать для `key` что-то другое

2022-07-16 22:04 UTC, pavelsokolov21 requested changes

2022-07-16 22:04 UTC, pavelsokolov21 commented on src/interfaces/search-form.ts
> +    id: string;
Используй уже готовый интерфейс!

2022-07-16 22:04 UTC, pavelsokolov21 commented on src/pages/home/components/search/components/select-where-destination/select-where-destination.tsx
> +  handleChangeWhere: any;
any

2022-07-16 22:04 UTC, pavelsokolov21 commented on src/pages/home/components/search/search-hooks.ts
> +  const handleChangeWhere = (arrayHelpers: FieldArrayRenderProps, index: number, value: any | null) => {
any

2022-07-16 22:04 UTC, pavelsokolov21 commented on src/pages/home/components/search/search.tsx
> +  const options: SearchDestination[] = i18n.language === LANGUAGES.RU ? RUdestinations : ENdestinations;
Эту переменную необязательно было переименовывать

2022-07-17 11:12 UTC, pavelsokolov21 approved these changes

2022-07-17 11:25 UTC, merged