feat: added route for client form page
TopTrip-ge/top-trip pull request #70
Opened 2022-07-26 08:37 UTC by KoTuK2306

2022-07-28 18:26 UTC, pavelsokolov21 requested changes

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-constants.ts
> +export const MINUTES = [
Создав функцию, которая фором сгенерит массив

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-constants.ts
> +export const HOURS = [
Создав функцию, которая фором сгенерит массив

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-hooks.ts
> +  const [hour, setHour] = useState<string>("");
не обязательно ставить тут дженерик, подхватит сам

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-hooks.ts
> +  const [minute, setMinute] = useState<string>("");
не обязательно ставить тут дженерик, подхватит сам

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-hooks-formik.ts
> +  const formik = useFormik<any>({
не `any`

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-hooks-formik.ts
> +    [BOOK_FIELD_NAMES.MAIL]: yup.string().min(4, t("too-short")).matches(mailRegExp, t("invalid-e-mail")),
`yup` умеет валидировать `email` из-под коробки https://www.abstractapi.com/guides/yup-email-validation-string-schema-code-examples

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-hooks-formik.ts
> +  const nameRegExp = /(?:\s|^)[\p{Alphabetic}\-._]+(?:\s|$)/u;
Какой-то страшный паттерн. Можно ли как-то проще?

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-hooks-formik.ts
> +    [BOOK_FIELD_NAMES.PHONE]: yup.string().min(4, t("too-short")).required(t("required")),
валидация для номера с помощью `yup`: https://stackoverflow.com/questions/52483260/validate-phone-number-with-yup

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/phone-input/phone-input-style.ts
> +    border-color: ${({ isvalid, theme: { colors } }) => (isvalid !== "false" ? colors.red : "")};
нужно погуглить и подумать, как обойти

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/phone-input/phone-input-style.ts
> +    border-color: ${({ isvalid, theme: { colors } }) => (isvalid !== "false" ? colors.red : "")};
нужно погуглить и подумать, как обойти

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/phone-input/phone-input.tsx
> +  const [value, setValue] = useState<string>("");
нет смысла от дженерика

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/phone-input/phone-input.tsx
> +  const [isValid, setIsValid] = useState<boolean>(false);
нет смысла от дженерика

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/phone-input/phone-input.tsx
> +          isvalid={(hasFieldError(BOOK_FIELD_NAMES.PHONE) || (!isValid && value !== "")).toString()}
вынеси условие в переменную, так как используется ниже и подумай, как обойти ворнинг

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/phone-input/phone-input-style.ts
> +  & .css-11nb985-MuiInputBase-root-MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline {
класс не работает, так как я тут вижу хеш `11nb985`, который явно генерируется

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/phone-input/phone-input-style.ts
> +  & .css-11nb985-MuiInputBase-root-MuiOutlinedInput-root:hover .MuiOutlinedInput-notchedOutline {
класс не работает, так как я тут вижу хеш 11nb985, который явно генерируется

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-hooks.ts
> +export const useForm = () => {
я думаю, нужно хук назвать более информативно, например `useOrderForm`

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-hooks.ts
> +      return formik.errors[field] as ReactNode;
мне кажется, что тут должен быть возвращаемый тип `string`, а каст уже делать в месте, где ругается на строку

2022-07-28 18:26 UTC, pavelsokolov21 commented on public/locales/en/client-form/sections.json
> +  "button.back": "Back",
это `common`

2022-07-28 18:26 UTC, pavelsokolov21 commented on public/locales/en/client-form/sections.json
> +  "button.book": "Book"
`common`

2022-07-28 18:26 UTC, pavelsokolov21 commented on public/locales/ru/client-form/validation.json
> +  "required": "Обязательное поле",
в общую валидацию всё, так как может быть ре-использовано

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/client-form.tsx
> +    <Form sx={{ mt: 3 }} />
назови более информативно, например `OrderForm`

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-hooks-formik.ts
> +  const mailRegExp = /@/;
так как `yup` умеет в валдицию `email`, мне кажется, что смысла в этом паттерне нет

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-hooks-formik.ts
> +    [BOOK_FIELD_NAMES.ADDRESS]: yup.string().min(4, t("too-short")).required(t("required")),
зачем нужен минимум, если и так стоит `required`? Если минимум нужен, почему именно 4?

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-hooks-formik.ts
> +    [BOOK_FIELD_NAMES.PHONE]: yup.string().min(4, t("too-short")).required(t("required")),
зачем нужен минимум, если и так стоит `required`? Если минимум нужен, почему именно 4?

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-hooks-formik.ts
> +    [BOOK_FIELD_NAMES.MAIL]: yup.string().min(4, t("too-short")).matches(mailRegExp, t("invalid-e-mail")),
И опять почему именно 4? Мне кажется, что можно без этого

2022-07-28 18:26 UTC, pavelsokolov21 commented on src/pages/client-form/components/phone-input/phone-input.tsx
> +        {(hasFieldError(BOOK_FIELD_NAMES.PHONE) || (!isValid && value !== "")) && (
вынеси условие в переменную, так как используется выше

2022-07-28 18:37 UTC, KoTuK2306 commented on src/pages/client-form/components/form/form-hooks-formik.ts
> +  const nameRegExp = /(?:\s|^)[\p{Alphabetic}\-._]+(?:\s|$)/u;
Это одно из самых коротких для валидации чисто букв без спец символов, что я нашёл

2022-07-28 19:08 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-hooks-formik.ts
> +  const nameRegExp = /(?:\s|^)[\p{Alphabetic}\-._]+(?:\s|$)/u;
https://stackoverflow.com/a/8059409/12661671 - это самая простая + добавить русские буквы

2022-08-02 19:56 UTC, pavelsokolov21 requested changes

2022-08-02 19:56 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-constants.ts
> +const fillTheArrayWithRequiredNumberOfNumbers = (numberOfNumbers: number): string[] => {
эту функцию лучше вынести в `form-utils.ts`

2022-08-02 19:56 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form.tsx
> +
лишний пробел. Я не помню, есть у нас договорённость ставить пробелы между бибками и нашими файлами. Мне кажется, что не стоит, но я могу путать

2022-08-02 19:56 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form.tsx
> +  const isValidForm = Object.keys(formik.errors).length === 0;
я бы создал функцию `isValidForm` в `utils/form.ts`, которая жрала бы ошибки или `formik` целиком и возвращала бы `boolean`. Так мы можем реиспользовать логику и не писать постоянно `Object.keys(formik.errors).length === 0`

2022-08-02 19:56 UTC, pavelsokolov21 commented on src/pages/client-form/components/phone-input/phone-input.tsx
> +export const PhoneInput: FC<Pick<UseOrderForm, "hasFieldError" | "getHelperErrorText" | "formik">> = ({
вынеси тип в `type Props = Pick<UseOrderForm, "hasFieldError" | "getHelperErrorText" | "formik">`

2022-08-02 19:56 UTC, pavelsokolov21 commented on src/pages/client-form/components/phone-input/phone-input.tsx
> +  const handleChange = (newValue: typeof value) => {
```suggestion
  const handleChange = (phone: string) => {

```

2022-08-02 19:56 UTC, KoTuK2306 commented on src/pages/client-form/components/form/form.tsx
> +
Это я случайно поставил, так что уберу

2022-08-03 12:22 UTC, pavelsokolov21 commented on src/utils/form.ts
> +export const isValidForm = (errors: FormikErrors<BookForm>) => Object.keys(errors).length === 0;
Я сейчас нашёл, что формик сам имеет поле `isValid`. Функция может быть посполезной https://formik.org/docs/api/formik#isvalid-boolean

2022-08-03 13:54 UTC, pavelsokolov21 approved these changes

2022-08-03 13:54 UTC, merged