feature/adaptive on tour information
TopTrip-ge/top-trip pull request #75
Opened 2022-08-08 10:18 UTC by KoTuK2306

2022-08-08 11:31 UTC, pavelsokolov21 requested changes

2022-08-08 11:31 UTC, pavelsokolov21 commented on src/pages/select-driver/components/drivers/components/driver-card/driver-card.tsx
> +          width: "288px",
значит ли это, что карточки стали шире и на больших размерах тоже? Нужно во всю ширину делать только при маленьких экранах. Плюс просто подгон - это плохо. Почему бы не юзать `100%`?

2022-08-08 11:32 UTC, KoTuK2306 commented on src/pages/select-driver/components/drivers/components/driver-card/driver-card.tsx
> +          width: "288px",
Рррриальна, ща сделаю

2022-08-09 11:57 UTC, pavelsokolov21 approved these changes

2022-08-09 11:57 UTC, merged