feat: removed mocks and added drivers requests
TopTrip-ge/top-trip pull request #85
Opened 2022-08-25 13:39 UTC by KoTuK2306

2022-08-25 14:11 UTC, pavelsokolov21 requested changes

2022-08-25 14:11 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/components/order-information/order-information-utils.ts
> +type Drivers = ({ id: string } & DocumentData)[];
```suggestion
interfaces Driver extends DocumentData {
  id: string;
}

```

2022-08-25 14:11 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/components/order-information/order-information-utils.ts
> +export const findPriceByOrderId = (drivers: Drivers, id: string | null) => {
```suggestion
export const findPriceByOrderId = (drivers: Driver[], id: string | null) => {

```

2022-08-25 14:11 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/form-utils.ts
> +type Drivers = ({ id: string } & DocumentData)[];
Повторяешь ебучий интерфейс!!! 😡

2022-08-26 13:15 UTC, pavelsokolov21 requested changes

2022-08-26 13:15 UTC, pavelsokolov21 commented on src/interfaces/firebase.ts
> +export interface FirebaseDriver extends DocumentData {
Разве водитель имеет только id? Я не могу понять, зачем этот интерфейс. Почему мы не можем использовать просто `Driver`?

2022-08-26 13:15 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/components/order-information/order-information-hooks.ts
> +  const [driver, setDriver] = useState<DocumentData | null>(null);
Судя по коду ниже, тут должен быть `Driver`, а не `DocumentData`

2022-08-26 13:15 UTC, pavelsokolov21 commented on src/pages/select-driver/components/drivers/components/driver-card/driver-card.tsx
> +  driver: DocumentData;
Мне кажется, тут должен быть `Driver`

2022-08-26 13:15 UTC, pavelsokolov21 commented on src/pages/select-driver/components/drivers/drivers.tsx
> +  const drivers = collectDataFromCollection(value);
Сюда нужно передать дженерик интерфейса водителя

2022-08-26 13:15 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/components/order-information/order-information-hooks.ts
> +      setDriver(driverResponse?.data() as Driver);
можно написать функицю, подобную `collectDataFromCollection`, но для документа

2022-08-26 14:52 UTC, pavelsokolov21 requested changes

2022-08-26 14:52 UTC, pavelsokolov21 commented on src/utils/collect-data-from-document.ts
> +export const collectDataFromDocument = <T = DocumentData>(collection?: DocumentSnapshot<T>) => collection?.data() ?? [];
Функция принимает документ, а не коллекцию. Возвращает не обязательно массив. Думай, когда пишешь код, пожалуйста. Подумай, как можно обработать дефолтное значение. Возможно, стоит передавать необязательный параметр второй, чтобы возвращать его, а не только массив

2022-08-26 14:52 UTC, pavelsokolov21 commented on src/pages/select-driver/components/drivers/drivers.tsx
> +  const drivers = collectDataFromCollection<Driver>(value as QuerySnapshot<Driver>);
Вместо каста доработай useCollection

2022-08-26 14:52 UTC, pavelsokolov21 commented on src/interfaces/driver.ts
> +export interface Driver extends DocumentData {
Так мы не можем переиспользовать Driver. Создай второй интерфейс на основе Driver тут же с другим именем

2022-08-26 14:52 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/components/order-information/order-information-hooks.ts
> +  const foundDriver = collectDataFromDocument(driverResponse);
Мне кажется, это нужно делать в useEffect, где уже есть проверка на существование driverResponse

2022-08-26 14:52 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/components/order-information/order-information-hooks.ts
> +      setDriver(foundDriver as Driver);
Вместо каста доработай useDocument

2022-08-26 19:40 UTC, pavelsokolov21 requested changes

2022-08-26 19:40 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/components/order-information/order-information-hooks.ts
> +    const foundDriver = collectDataFromDocument(driverResponse as DocumentSnapshot<Driver>);
Пусть useDocument сразу возвращает первый аргумент массива с этим типом, чтобы не делать вечно касты

2022-08-26 19:40 UTC, pavelsokolov21 commented on src/pages/client-form/components/form/components/order-information/order-information-hooks.ts
> +    convertCurrency(driver?.price as number, currency).then((data) => setPrice(data));
Зачем тут каст. В driver price уже число должно быть

2022-08-26 19:41 UTC, KoTuK2306 commented on src/pages/client-form/components/form/components/order-information/order-information-hooks.ts
> +    convertCurrency(driver?.price as number, currency).then((data) => setPrice(data));
Я забыл про это место

2022-08-26 20:30 UTC, pavelsokolov21 approved these changes

2022-08-26 20:30 UTC, merged